name: CI DEVELOP
on:
  pull_request:
    branches:
      - develop
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Jest and dependencies
        run: npm install jest @types/jest ts-jest --save-dev

      - run: npm run test
